### PR TITLE
Add build for all pull requests on GitHub

### PR DESCRIPTION
**Pull request by derkoe**
This builds the whole project fro each pull request on GitHub. This makes it a lot easier to check the correctness contributions.

### CODE REVIEW

**Review by benweidig — CHANGES_REQUESTED** [review]
Hi @derkoe,

thanks for the PR.

Adding an action on pull-request-only seems like a good idea, so any contributor gets instant feedback.

However, the job should run with a strategy matrix for all versions Tapestry supports (8-17).
Either you can add it to the PR, or I'll do it this weekend if I find the time.

**Comment by derkoe** [comment]
@benweidig added the matrix to the build

**Comment by derkoe** [comment]
I'm not quite sure why GitHub is not executing the action on this PR. Maybe a member of the tapestry-5 team has to create the PR for the job to run!?

**Review by benweidig — APPROVED** [review]
Thanks for adding the matrix.
Not sure why it's not running automatically on the PR... let's see if this is still the case after merging.

**Comment by benweidig** [comment]
It seems Apache does not allow all actions.
browser-actions/setup-firefox@v1 and browser-actions/setup-geckodriver@latest don't match the allowed ones, as seen in this run on another PR run: https://github.com/apache/tapestry-5/actions/runs/6576630495

I'm going to ask the on the Apache Infrastructure Slack how this could be resolved.

Here the run annotation for reference.

```
browser-actions/setup-firefox@v1 and browser-actions/setup-geckodriver@latest are not allowed to be used in apache/tapestry-5. Actions in this workflow must be: within a repository owned by apache, created by GitHub, verified in the GitHub Marketplace, or matching the following: */*@[a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9][a-f0-9]+, AdoptOpenJDK/install-jdk@*, JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92, TobKed/label-when-approved-action@*, actions-cool/issues-helper@*, actions-rs/*, al-cheb/configure-pagefile-action@*, amannn/action-semantic-pull-request@*, apache/*, burrunan/gradle-cache-action@*, bytedeco/javacpp-presets/.github/actions/*, chromaui/action@*, codecov/codecov-action@*, conda-incubator/setup-miniconda@*, container-tools/kind-action@*, container-tools/microshift-action@*, dawidd6/action-download-artifact@*, delaguardo/setup-graalvm@*, docker://jekyll/jekyll:*, docker://pandoc/core:2.9, eps1lon/actions-label-merge-conflict@*, ...
```

**Comment by benweidig** [comment]
For reference: https://issues.apache.org/jira/projects/INFRA/issues/INFRA-25108

**Pull request merged**
